/*--FILE HEADER-(set tabulator to 4)-------------------------------------------
;
;   filename    : ERRLOG.SUB  
;   version     : 0003
;   contents    : Definition of subsystem for errorlogger task
;   author      : K.P.H.
;   date        : Feb 27, 1995
;
;---FUNCTION AND RMOS ENVIRONMENT----------------------------------------------
;
;   function    : Definition of subsystem for ERRLOG.C
;
;   RMOS2 & RMOS3
;
;---END OF FILE HEADER---------------------------------------------------------
;
;---MODIFICATION HEADER--------------------------------------------------------
;
;   Oct 14, 1991  R.S.  0001  Original issue
;   Dec  4, 1992  W.S.  0002  New Header added
;   Feb 27, 1995  K.P.H.0003  Removed subsystem for x_cr_sys_device and unit
;
;---END OF MODIFICATION HEADER-----------------------------------------------*/

$compact (errlog -const in code- has errlog; exports xerrlogtask)
