/*--FILE HEADER----------------------------------------------------------------
;
;   filename    : RMCONF.H
;   version     : 0001
;   contents    : Include-File for RMOS-Configuration in C
;   author      : K.P.H.
;   date        : Jan 12, 1995
;
;---FUNCTION AND RMOS ENVIRONMENT----------------------------------------------
;
;   function    : Include-file for RMOS-Configuration
;
;   RMOS2 & RMOS3
;
;---END OF FILE HEADER---------------------------------------------------------
;
;---MODIFICATION HEADER--------------------------------------------------------
;
;   Jan 12, 1995  K.P.H. 0001  Original issue 
;
;---END OF MODIFICATION HEADER-----------------------------------------------*/

#ifndef _RMCONF_H_
#define _RMCONF_H_

#ifndef _PROT_H_
#include <prot.h>
#endif
#ifndef _RMCOMP_H_
#include <rmcomp.h>
#endif
#ifndef _MISC86_H_
#include <misc86.h>
#endif
#ifndef _RMAPI_H_
#include <rmapi.h>
#endif
#ifndef _RCINC_H_
#include <rcinc.h>
#endif
#ifndef _DRVSPEC_H_
#include <drvspec.h>
#endif
#ifndef _RMNAMES_H_
#include <rmnames.h>
#endif

#endif /* _RMCONF_H_ */

